-- Enable Row Level Security on all tables
ALTER TABLE gyms ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_colors ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_logos ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_elements ENABLE ROW LEVEL SECURITY;